

const char* DEVICE_NAME [] = { "Часы на накальных индикаторах ИВ-13", "Iv-13 numetron clock"};
const char* TAB_LINKS_NAMES [] = {"Главная,Настройки,Инфо,Прошивка", "Home,Setting,Info,Firmware"};
const char* SETTING_LANGUAGE [] = {"Язык", "Language"};
const char* SETTING_LANGUAGE_ARRAY = "  RU  ,  EN  ";
const char* SETTING_NETWORK_CONNECTION [] = {"Подключение к сети","Network connection" };
const char* SETTING_NETWORK_WIFI_NAME []={"Имя сети:", "WiFi name:"};
const char* SETTING_NETWORK_WIFI_PASSWORD []={"Пароль:","Password:"};
const char* SETTING_OP_NAME []={"Openweathermap.org","Openweathermap.org"};
const char* SETTING_OP_APIKEY[]={"Api ключ:","Api Key:"};
const char* SETTING_OP_CITY []={"Город(eng):","City:"};
const char* SETTING_TIMEZONE_NAME []={"Часовой пояс:","Time zone:"};
const char* SETTING_TIMEZONE_GMT = "GMT-12,GMT-11,GMT-10,GMT-9,GMT-8,GMT-7,GMT-6,GMT-5,GMT-4,GMT-3,GMT-2,GMT-1,GMT+0,GMT+1,GMT+2,GMT+3,GMT+4,GMT+5,GMT+6,GMT+7,GMT+8,GMT+9,GMT+10,GMT+11,GMT+12";
const char* SETTING_SAVE_BUTTON []={"Сохранить", "Save"};
const char* SETTING_NTP_NAME []={"Сервер NTP:", "Server NTP:"};
const char* SETTING_TIME_NAME []={"Настройка времени", "Time setting"};
const char* SETTING_NTP_SYNC_BTN []={"Синхронизовать", "Synchronize"};
const char* SETTING_OP_SYNC_BTN [] = {"Обновить","Update"};
const char* SETTING_WIFI_CONNECT_BTN [] = {"Подключить","Connect"};

const char* SETTING_NAROD_NAME []={"Narodmon.ru","Narodmon.ru"};
const char* SETTING_NAROD_APIKEY[]={"Api ключ:","Api Key:"};
const char* SETTING_NAROD_ID[]={"ID прибора:","Divice ID:"};
const char* SETTING_NAROD_SYNC_BTN []={"Обновить","Update"};
const char* SETTING_NAROD_SENSORS_LABEL []={"Номер датчика","Sensor number"};
const char* SETTING_NAROD_SENSOR_1 []={"Температура:","Temperature:"};
const char* SETTING_NAROD_SENSOR_2 []={"Влажность:","Humidity:"};
const char* SETTING_NAROD_SENSOR_3 []={"Давление:","Pressure:"};
const char* SETTING_NAROD_SENSORS []={",Температура,Влажность,Давление,Радиация",",Temperature,Humidity,Pressure,Radiation"};
const char* SET_TEMPERATURE_SENSOR_NAME []={"Датчик темпр.: ","Temp. sensor: "};
char SET_TEMPERATURE_SENSOR_ARRAY []={"Здесь датчики для вывода в селект"};
const char* DISPLAY_DOTS_NAME []={"Анимация точек:","Dots animations:"};
const char* DISPLAY_DOTS_ANIMATIONS []={"1,2,3","1,2,3"};//"Последовательно,2 одновременно,2 попеременно","Consistently,Simultaneously,Alternately"};
const char* DISPLAY_DOTS_RANDOM_SWITCH []={"Случ. анимация","Random animations"};
const char* DISPLAY_SECONDS_SWITCH []={"Вкл/выкл секунды","On/off seconds"};
const char* DATA_TYPE_SENSOR = ",t воздуха,t воды,t почвы,t точка росы,RH влажность,атм.давл.,освещенн.,Яркость,УФ-индекс,радиация,осадки,Пы,скорость,направление,концентрация,Р мощность,U напряжение,I сила тока,А энергия, % батареи,Rx, Tx трафик,логический,dBm сигнал,водосчетчик,время работы,числовой,текстовый";
const char* DISPLAY_DATA_LABEL []={"Данные дисплея","Display data"};
const char* DISPLAY_DATA_SHOW_SWITCH []={"Автопоказ","Auto show"};